### ISSUE TITLE
pockets.py returning None for no-pockets breaks FAST-pockets

### ISSUE THREAD

**Issue by Justin-J-Miller** [bowman-lab/enspara#220]
@ameller1994 @mizimmer90 
Wanted to raise this as an issue to solicit thoughts on best recourse. This commit:
https://github.com/bowman-lab/enspara/commit/c0197066e025a8bfe0b760e45b473201690f5347

switched `enspara/geometry/pockets.py` to returning `None` if there are no pockets found in a structure. If found in FAST-pockets, this breaks `fast/analysis/pockets.py` as FAST is expecting a MDTraj object. Error trace at the end of this issue. @ameller1994 I assume this is a useful commit that we'd prefer not revert?

@lgsmith and I briefly discussed this and think the best course is to have FAST run a check to see if it's getting a MDtraj object or `None`. 

Currently, in the course of 0 pockets, FAST returns the following:
`pocket_sizes.dat` containing the int `0`
`stateXXXXXXX_pockets.pdb` containing:

```
MODEL        0
ENDMDL
END
```

Any/all thoughts welcome!

Error trace (from FAST)-
```
Traceback (most recent call last):
  File "/home/justinjm/miniconda3/envs/enspara/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/justinjm/miniconda3/envs/enspara/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/export/seas-home/justinjm/software/fast/analysis/pockets.py", line 47, in _save_pocket_element
    pocket_element.save_pdb(pok_output_name)
AttributeError: 'NoneType' object has no attribute 'save_pdb'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "analysis.py", line 4, in <module>
    c.run()
  File "/export/seas-home/justinjm/software/fast/analysis/pockets.py", line 283, in run
    self.output_folder, self.n_cpus)
  File "/export/seas-home/justinjm/software/fast/analysis/pockets.py", line 72, in save_pocket_elements
    pool.map(_save_pocket_element, save_info)
  File "/home/justinjm/miniconda3/envs/enspara/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/justinjm/miniconda3/envs/enspara/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
AttributeError: 'NoneType' object has no attribute 'save_pdb'
```

**Comment by Justin-J-Miller** [comment]
I've raised a PR on FAST's repo that implements the above check in the event that's the route we want to go. 

https://github.com/bowman-lab/fast/pull/4

**Comment by Justin-J-Miller** [comment]
Closing this issue as the FAST PR has been merged.
