### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by philippschnee** [bowman-lab/enspara#240]
Dear all,

I want to test enspara for backbone clustering of protein trajectories. However, when i ran through the tutorial, i came across this error:

```
(enspara) psc@psc-linux:~/enspara$ enspara cluster \
  --trajectories trajectory-*.xtc \
  --topology fs-peptide.pdb \
  --algorithm khybrid \
  --cluster-number 20 \
  --subsample 10 \
  --atoms '(name N or name C or name CA)' \
  --distances ./fs-khybrid-clusters0020-distances.h5 \
  --center-features ./fs-khybrid-clusters0020-centers.pickle \
  --assignments ./fs-khybrid-clusters0020-assignments.h5
INFO:numexpr.utils:NumExpr defaulting to 12 threads.
Authorization required, but no authorization protocol specified

Authorization required, but no authorization protocol specified

Authorization required, but no authorization protocol specified

Authorization required, but no authorization protocol specified

Traceback (most recent call last):
  File "/home/philipp/miniconda3/envs/enspara/bin/enspara", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/philipp/miniconda3/envs/enspara/lib/python3.12/site-packages/enspara/apps/main.py", line 44, in main
    args = identify_app(argv)
           ^^^^^^^^^^^^^^^^^^
  File "/home/philipp/miniconda3/envs/enspara/lib/python3.12/site-packages/enspara/apps/main.py", line 23, in identify_app
    while h in argv and argv.index(h) != 1:
          ^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
 ```

i did follow the installation, except, that i did:

```
conda install -c conda-forge mdtraj cython
```

instead of:

```
conda install mdtraj cython
```

**Comment by Justin-J-Miller** [comment]
Hey there!

I suspect this issue is not the installation pathway but that we've got something broken in `main.py`. This looks similar to https://github.com/bowman-lab/enspara/issues/204. I'll try and root out what is going awry, in the meantime you should be able to pass the same arguments to `cluster.py`.

Instead of using `enspara cluster` you'd use `python /path/to/enspara/enspara/apps/cluster.py`.
